// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CalculatorController from "./calculator_controller";
application.register("calculator", CalculatorController);

import UiController from "./ui_controller";
application.register("ui", UiController);
