// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import IndexRentCalculatorController from "./index_rent_calculator_controller"
application.register("index-rent-calculator", IndexRentCalculatorController)

import UiController from "./ui_controller"
application.register("ui", UiController)
